name: ci
on: [ push, pull_request ]
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: test
        run: |
          chmod 0600 $GITHUB_WORKSPACE/vendor/vendor-ios/src/test/resources/fixtures/derived-data-manager/test_rsa
          ./gradlew clean test jacocoTestReport integrationTest
          bash <(curl -s https://codecov.io/bash)
      - name: detekt
        run: |
          ./gradlew clean detektCheck
      - name: deliver maven
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop' }}
        run: |
          bash .buildsystem/deploy-sonatype.sh
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: assemble cli
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          ./gradlew :cli:assembleDist -PreleaseMode=RELEASE
      - name: deliver cli
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: deliver cli snapshot
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          ./gradlew :cli:publishDistZipPublicationToGitHubRepository -PreleaseMode=SNAPSHOT
        env:
          GITHUB_MAVEN_USERNAME: ${{ secrets.GH_MAVEN_USERNAME }}
          GITHUB_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
