name: deploy-cli-snapshot
on:
  push:
    branches:
      - develop
    tags-ignore:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: deploy-cli-snapshot-to-github
        run: ./gradlew :cli:publishDefaultPublicationToGitHubRepository -PreleaseMode=SNAPSHOT
        env:
          GITHUB_MAVEN_USERNAME: ${{ secrets.GH_MAVEN_USERNAME }}
          GITHUB_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
